module.exports = {
	globalFilter:{
		"ce":'connector.entryHandler.',
		"fw":"fruitWheel.fruitWheelHandler.",
		"tt":"transfer.transferHandler.",
		"dd":"diceBao.diceBaoHandler.",
		"mm":"manager.managerHandler.",
		"sg":"Scratch.ScratchHandler.",
		"fs":"fruitSlot.fruitSlotHandler."
	},
	gameFilter:{
	    "B":"bet",
	    "I":"GetGameID", 
	    "M":"GetMoney",
	    "T":"GetTimeZone",
	    "H":"GetHistory",
	    "S":"GetStatus",
	    "O":"GetBetTotal",
	    "A":"AddtoChannel",
	    "L":"LeaveChannel",
	    "G":"GetGameSet"
	}
}